### ISSUE TITLE
Bug while creating HTML table with links.

### ISSUE THREAD

**Issue by AmericanY** [prettytable/prettytable#103]
```python
from prettytable import PrettyTable


listsites1 = ["1", "2"]

table1 = PrettyTable()
table1.field_names = ['Links']
table1.add_rows(listsites1)
print(table1)


listsites2 = ["https://www.x.com", "https://www.x.com"]

table2 = PrettyTable()
table2.field_names = ['Links']
table2.add_rows(listsites2)
# solution  --> table2.add_rows(map(lambda x: [x], listsites2))
print(table2)
```

Output:

```
+-------+
| Links |
+-------+
|   1   |
|   2   |
+-------+
Traceback (most recent call last):
  File "c:\Users\AmericaN\Desktop\Lab\learn.py", line 16, in <module>
    table2.add_rows(listsites2)
  File "C:\Users\AmericaN\Desktop\Lab\MyEnv\lib\site-packages\prettytable\prettytable.py", line 1025, in add_rows
    self.add_row(row)
  File "C:\Users\AmericaN\Desktop\Lab\MyEnv\lib\site-packages\prettytable\prettytable.py", line 1037, in add_row
    raise Exception(
Exception: Row has incorrect number of values, (actual) 17!=1 (expected)
```

**Comment by hugovk** [comment]
`add_rows` is expecting an iterable of lists:

```pycon
>>> from prettytable import PrettyTable
>>> help(PrettyTable.add_rows)
Help on function add_rows in module prettytable.prettytable:

add_rows(self, rows)
    Add rows to the table

    Arguments:

    rows - rows of data, should be an iterable of lists, each list with as many
    elements as the table has fields

>>>
```

From the [README](https://github.com/jazzband/prettytable#all-rows-at-once):

> When you have a list of rows, you can add them in one go with `add_rows`:

```python
x.field_names = ["City name", "Area", "Population", "Annual Rainfall"]
x.add_rows(
    [
        ["Adelaide", 1295, 1158259, 600.5],
        ["Brisbane", 5905, 1857594, 1146.4],
        ["Darwin", 112, 120900, 1714.7],
        ["Hobart", 1357, 205556, 619.5],
        ["Sydney", 2058, 4336374, 1214.8],
        ["Melbourne", 1566, 3806092, 646.9],
        ["Perth", 5386, 1554769, 869.4],
    ]
)
```

So the fix is to use a list of lists:

```diff

from prettytable import PrettyTable


-listsites1 = ["1", "2"]
+listsites1 = [["1"], ["2"]]

table1 = PrettyTable()
table1.field_names = ['Links']
table1.add_rows(listsites1)
print(table1)


-listsites2 = ["https://www.x.com", "https://www.x.com"]
+listsites2 = [["https://www.x.com"], ["https://www.x.com"]]

table2 = PrettyTable()
table2.field_names = ['Links']
table2.add_rows(listsites2)
print(table2)
```

Output:

```
+-------+
| Links |
+-------+
|   1   |
|   2   |
+-------+
+-------------------+
|       Links       |
+-------------------+
| https://www.x.com |
| https://www.x.com |
+-------------------+
```
