### ISSUE TITLE
Header with special chars cause an exception on render

### ISSUE THREAD

**Issue by vit1251** [prettytable/prettytable#122]
Use Debian version as header fields and cause an exception:

```
Traceback (most recent call last):
  File "./make_report.py", line 128, in <module>
    app.run()
  File "./make_report.py", line 73, in run
    self.makeCaseReport(projectKey, caseKey)
  File "./make_report.py", line 108, in makeCaseReport
    self.makeReports(caseKey, rows, versions)
  File "./make_report.py", line 120, in makeReports
    output = x.get_string()
  File "/usr/local/lib/python3.7/dist-packages/prettytable/prettytable.py", line 1312, in get_string
    lines.append(self._stringify_header(options))
  File "/usr/local/lib/python3.7/dist-packages/prettytable/prettytable.py", line 1414, in _stringify_header
    + " " * rpad
```

Key example: "15.23.2323-dev-20+deb10"

**Comment by hugovk** [comment]
Please can you provide a self-contained code snippet that reproduces the problem?

**Comment by vit1251** [comment]
Source code from snippet use internal attribute field_header instead common API.
My error. Sorry.
